on:
  pull_request:
    types:
    - closed

name: AzurePipelineApply

jobs:
  azure-deploy-resources:
      runs-on: ubuntu-latest
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      steps:
      
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.3.7
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform"
        env:
          TF_VAR_ssh_pub_key: ${{ secrets.SSH_PUB_KEY }}
      
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.3.7
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./terraform"
          args: '-var-file="./demo.tfvars"'
        env:
          TF_VAR_ssh_pub_key: ${{ secrets.SSH_PUB_KEY }} 
    
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.3.7
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform"
          args: '-var-file="./demo.tfvars"'
        env:
          TF_VAR_ssh_pub_key: ${{ secrets.SSH_PUB_KEY }}    
